### PR TITLE
Parallax carousel

### PR DESCRIPTION
**Pull request by nishchay-veer**
fixing parallax and carousel in about section

### CODE REVIEW

**Review by parteekcoder — COMMENTED** [review]
@nishchay-veer the parallax is working fine. Can you please share what changes are doing and what issue they are fixing?

**Comment by nishchay-veer** [comment]
No, it isn't . wait I'll share

**Comment by parteekcoder** [comment]
> No, it isn't . wait I'll share

I checked this in mobile , tab , desktop view. It is working good. But You can share the issue you discovered.

**Comment by nishchay-veer** [comment]
Screenshot from 2024-01-31 22-19-12
See this, there is an empty space between the mid image and bottom image in desktop, its't not much visible in mobile

**Comment by nishchay-veer** [comment]
I'm trying to fix it, don't merge it now.  there are some issues that I'm resolving

**Comment by nishchay-veer** [comment]
can merge this now

**Review by parteekcoder — APPROVED** [review]

**Pull request merged**
